### PR TITLE
Advertise TOTP instead of Google

### PR DESCRIPTION
**Pull request by helmo**
As this plugin does RFC 6238 and not really anything Google specific it seems better to describe it that way.

It would also be nice to link to a list of free clients.

### CODE REVIEW

**Comment by alexandregz** [comment]
Merged, thx!. You're right, it's a TOTP "app" (plugin), not a Google app

**Comment by alexandregz** [comment]
Do you have some links about free clients?

**Comment by helmo** [comment]
I use https://fedorahosted.org/freeotp/ (also available on
https://f-droid.org/repository/browse/?fdfilter=otp&fdid=org.fedorahosted.freeotp)


I'm hesitant to start 'maintaining' a list of apps here. The best list I
could find is
https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm#Client_implementations

-- 

Met vriendelijke groet / Regards,

Herman van Rink
Initfour websolutions

**Comment by alexandregz** [comment]
It's fine, I'm going to put a link, thx!

**Pull request merged**
